- name: Comment out any occurrences of kernel.modules_disabled from config files
  replace:
    path: '{{ item.path }}'
    regexp: ^[\s]*kernel.modules_disabled
    replace: '#kernel.modules_disabled'
  loop: '{{ find_sysctl_d.files }}'
  when:
  - disable_strategy | bool
  - low_complexity | bool
  - medium_disruption | bool
  - medium_severity | bool
  - reboot_required | bool
  - sysctl_kernel_modules_disabled | bool
  - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman", "container"]
  tags:
  - CCE-83397-0
  - disable_strategy
  - low_complexity
  - medium_disruption
  - medium_severity
  - reboot_required
  - sysctl_kernel_modules_disabled

