- name: Ensure talk-server is removed
  package:
    name: talk-server
    state: absent
  tags:
  - CCE-82180-1
  - disable_strategy
  - low_complexity
  - low_disruption
  - medium_severity
  - no_reboot_needed
  - package_talk-server_removed
  when:
  - disable_strategy | bool
  - low_complexity | bool
  - low_disruption | bool
  - medium_severity | bool
  - no_reboot_needed | bool
  - package_talk_server_removed | bool

