- name: Ensure All World-Writable Directories Are Owned by root User - Create List of World Writable Directories Not Owned
    by root
  ansible.builtin.set_fact:
    world_writable_dirs: '{{ world_writable_dirs | union(item.stdout_lines) | list }}'
  loop: '{{ result_found_dirs.results }}'
  tags:
  - CCE-83375-6
  - DISA-STIG-RHEL-08-010700
  - dir_perms_world_writable_root_owned
  - low_complexity
  - medium_disruption
  - medium_severity
  - no_reboot_needed
  - restrict_strategy
  when:
  - DISA_STIG_RHEL_08_010700 | bool
  - dir_perms_world_writable_root_owned | bool
  - low_complexity | bool
  - medium_disruption | bool
  - medium_severity | bool
  - no_reboot_needed | bool
  - restrict_strategy | bool

