- name: Set Interval For Counting Failed Password Attempts - Check if system relies on authselect tool
  ansible.builtin.stat:
    path: /usr/bin/authselect
  register: result_authselect_present
  when:
  - DISA_STIG_RHEL_08_020012 | bool
  - DISA_STIG_RHEL_08_020013 | bool
  - accounts_passwords_pam_faillock_interval | bool
  - low_complexity | bool
  - low_disruption | bool
  - medium_severity | bool
  - no_reboot_needed | bool
  - restrict_strategy | bool
  - '"pam" in ansible_facts.packages'
  tags:
  - CCE-80669-5
  - DISA-STIG-RHEL-08-020012
  - DISA-STIG-RHEL-08-020013
  - NIST-800-53-AC-7(a)
  - NIST-800-53-CM-6(a)
  - accounts_passwords_pam_faillock_interval
  - low_complexity
  - low_disruption
  - medium_severity
  - no_reboot_needed
  - restrict_strategy

