- name: Ensure All World-Writable Directories Are Owned by root User - Increment Search Paths List with Local NFS File System
    Targets
  ansible.builtin.set_fact:
    search_paths: '{{ search_paths | union([item.device.split('':'')[1]]) }}'
  loop: '{{ ansible_mounts }}'
  when:
  - DISA_STIG_RHEL_08_010700 | bool
  - dir_perms_world_writable_root_owned | bool
  - low_complexity | bool
  - medium_disruption | bool
  - medium_severity | bool
  - no_reboot_needed | bool
  - restrict_strategy | bool
  - item.device is search("localhost:")
  tags:
  - CCE-83375-6
  - DISA-STIG-RHEL-08-010700
  - dir_perms_world_writable_root_owned
  - low_complexity
  - medium_disruption
  - medium_severity
  - no_reboot_needed
  - restrict_strategy

